// Auto-generated medical center chart of accounts (137 accounts).
// Source: شجرة_الحسابات_مركز_طبي_كامل (ZATCA-compliant).
import type { Account } from "./erp-store";

export const MEDICAL_COA: Account[] = [
  { code: "1000", name_ar: "الأصول", name_en: "الأصول", type: "asset", level: "root", desc: "الأصول الكلية للمركز" },
  { code: "1100", name_ar: "الأصول المتداولة", name_en: "الأصول المتداولة", type: "asset", level: "group", parent: "1000", desc: "الأصول قابلة للتحويل إلى نقد خلال سنة" },
  { code: "1101", name_ar: "النقدية في الخزينة", name_en: "النقدية في الخزينة", type: "asset", level: "detail", parent: "1100", desc: "الأموال النقدية المتوفرة في الخزينة" },
  { code: "1102", name_ar: "الحساب البنكي الرئيسي", name_en: "الحساب البنكي الرئيسي", type: "asset", level: "detail", parent: "1100", desc: "الرصيد في البنك الأساسي للمركز" },
  { code: "1103", name_ar: "الحساب البنكي الثانوي", name_en: "الحساب البنكي الثانوي", type: "asset", level: "detail", parent: "1100", desc: "الرصيد في البنك الثانوي" },
  { code: "1110", name_ar: "ذمم المدينين", name_en: "ذمم المدينين", type: "asset", level: "group", parent: "1100", desc: "الفواتير المستحقة من المرضى والتأمينات" },
  { code: "1111", name_ar: "ذمم المرضى الشخصيين", name_en: "ذمم المرضى الشخصيين", type: "asset", level: "detail", parent: "1110", desc: "الفواتير المستحقة من المرضى مباشرة" },
  { code: "1112", name_ar: "ذمم شركات التأمين الصحي", name_en: "ذمم شركات التأمين الصحي", type: "asset", level: "detail", parent: "1110", desc: "المبالغ المستحقة من شركات التأمين" },
  { code: "1113", name_ar: "ذمم جهات حكومية صحية", name_en: "ذمم جهات حكومية صحية", type: "asset", level: "detail", parent: "1110", desc: "المبالغ المستحقة من الجهات الحكومية" },
  { code: "1120", name_ar: "المخزون السلعي", name_en: "المخزون السلعي", type: "asset", level: "group", parent: "1100", desc: "الأدوية والمستهلكات الطبية المخزنة" },
  { code: "1121", name_ar: "مخزون الأدوية والعقاقير", name_en: "مخزون الأدوية والعقاقير", type: "asset", level: "detail", parent: "1120", desc: "الأدوية والعقاقير الموجودة في الصيدلية" },
  { code: "1122", name_ar: "مخزون المستهلكات الطبية", name_en: "مخزون المستهلكات الطبية", type: "asset", level: "detail", parent: "1120", desc: "المستهلكات الطبية مثل الإبر والقطن" },
  { code: "1123", name_ar: "مخزون قطع الغيار والملحقات", name_en: "مخزون قطع الغيار والملحقات", type: "asset", level: "detail", parent: "1120", desc: "قطع الغيار والملحقات للمعدات الطبية" },
  { code: "1130", name_ar: "الدفعات المقدمة والمصروفات المدفوعة مقدماً", name_en: "الدفعات المقدمة والمصروفات المدفوعة مقدماً", type: "asset", level: "detail", parent: "1100", desc: "الدفعات المقدمة للموردين والإيجارات والتأمينات" },
  { code: "1140", name_ar: "ضرائب ورسوم قابلة للاسترجاع", name_en: "ضرائب ورسوم قابلة للاسترجاع", type: "asset", level: "detail", parent: "1100", desc: "ضريبة القيمة المضافة المدفوعة القابلة للاسترجاع" },
  { code: "1200", name_ar: "الأصول الثابتة", name_en: "الأصول الثابتة", type: "asset", level: "group", parent: "1000", desc: "الأصول غير المتداولة طويلة الأجل" },
  { code: "1210", name_ar: "العقارات والمباني", name_en: "العقارات والمباني", type: "asset", level: "detail", parent: "1200", desc: "العقار والمبنى الذي يشغله المركز" },
  { code: "1211", name_ar: "المعدات الطبية الثقيلة", name_en: "المعدات الطبية الثقيلة", type: "asset", level: "detail", parent: "1200", desc: "الأشعات والتحاليل والأجهزة الطبية الكبيرة" },
  { code: "1212", name_ar: "الأثاث والتجهيزات الطبية", name_en: "الأثاث والتجهيزات الطبية", type: "asset", level: "detail", parent: "1200", desc: "الكراسي الطبية والأسرة والتجهيزات" },
  { code: "1213", name_ar: "أجهزة الحاسوب والمكاتب", name_en: "أجهزة الحاسوب والمكاتب", type: "asset", level: "detail", parent: "1200", desc: "أجهزة الكمبيوتر والطابعات والمكاتب" },
  { code: "1214", name_ar: "المركبات والسيارات", name_en: "المركبات والسيارات", type: "asset", level: "detail", parent: "1200", desc: "السيارات والمركبات الخاصة بالمركز" },
  { code: "1215", name_ar: "رخص وتراخيص الممارسة الطبية", name_en: "رخص وتراخيص الممارسة الطبية", type: "asset", level: "detail", parent: "1200", desc: "رخص الممارسة الطبية والموافقات الحكومية" },
  { code: "1220", name_ar: "مراكمة استهلاك - العقارات", name_en: "مراكمة استهلاك - العقارات", type: "asset", level: "contra", parent: "1200", desc: "الاستهلاك المراكم لقيمة العقار" },
  { code: "1221", name_ar: "مراكمة استهلاك - المعدات الطبية", name_en: "مراكمة استهلاك - المعدات الطبية", type: "asset", level: "contra", parent: "1200", desc: "الاستهلاك المراكم للمعدات الطبية" },
  { code: "1222", name_ar: "مراكمة استهلاك - الأثاث والتجهيزات", name_en: "مراكمة استهلاك - الأثاث والتجهيزات", type: "asset", level: "contra", parent: "1200", desc: "الاستهلاك المراكم للأثاث والتجهيزات" },
  { code: "1223", name_ar: "مراكمة استهلاك - أجهزة الحاسوب", name_en: "مراكمة استهلاك - أجهزة الحاسوب", type: "asset", level: "contra", parent: "1200", desc: "الاستهلاك المراكم لأجهزة الحاسوب" },
  { code: "1224", name_ar: "مراكمة استهلاك - المركبات", name_en: "مراكمة استهلاك - المركبات", type: "asset", level: "contra", parent: "1200", desc: "الاستهلاك المراكم للمركبات" },
  { code: "1300", name_ar: "الأصول غير الملموسة", name_en: "الأصول غير الملموسة", type: "asset", level: "group", parent: "1000", desc: "الحقوق والبرامج والعلاقات التجارية" },
  { code: "1301", name_ar: "البرامج والأنظمة المحاسبية", name_en: "البرامج والأنظمة المحاسبية", type: "asset", level: "detail", parent: "1300", desc: "برامج النظام الطبي والمحاسبي" },
  { code: "1302", name_ar: "براءات الاختراع والحقوق الطبية", name_en: "براءات الاختراع والحقوق الطبية", type: "asset", level: "detail", parent: "1300", desc: "براءات الاختراع والحقوق الفكرية" },
  { code: "2000", name_ar: "الالتزامات", name_en: "الالتزامات", type: "liability", level: "root", desc: "الالتزامات الكلية للمركز" },
  { code: "2100", name_ar: "الالتزامات قصيرة الأجل", name_en: "الالتزامات قصيرة الأجل", type: "liability", level: "group", parent: "2000", desc: "الالتزامات المستحقة الدفع خلال سنة" },
  { code: "2110", name_ar: "ذمم الدائنين", name_en: "ذمم الدائنين", type: "liability", level: "group", parent: "2100", desc: "حسابات الموردين والشركات المورّدة" },
  { code: "2111", name_ar: "ذمم موردي الأدوية والمستهلكات", name_en: "ذمم موردي الأدوية والمستهلكات", type: "liability", level: "detail", parent: "2110", desc: "المبالغ المستحقة لموردي الأدوية" },
  { code: "2112", name_ar: "ذمم موردي الخدمات والصيانة", name_en: "ذمم موردي الخدمات والصيانة", type: "liability", level: "detail", parent: "2110", desc: "المبالغ المستحقة لشركات الصيانة والخدمات" },
  { code: "2113", name_ar: "ذمم موردي المعدات والتجهيزات", name_en: "ذمم موردي المعدات والتجهيزات", type: "liability", level: "detail", parent: "2110", desc: "المبالغ المستحقة لموردي المعدات" },
  { code: "2120", name_ar: "المستحقات والرواتب والأجور", name_en: "المستحقات والرواتب والأجور", type: "liability", level: "group", parent: "2100", desc: "الرواتب والأجور والمستحقات الموظفين" },
  { code: "2121", name_ar: "رواتب الموظفين مستحقة الدفع", name_en: "رواتب الموظفين مستحقة الدفع", type: "liability", level: "detail", parent: "2120", desc: "رواتب الموظفين غير المدفوعة" },
  { code: "2122", name_ar: "مكافآت نهاية الخدمة مستحقة", name_en: "مكافآت نهاية الخدمة مستحقة", type: "liability", level: "detail", parent: "2120", desc: "مكافآت نهاية الخدمة المستحقة" },
  { code: "2123", name_ar: "بدلات وتعويضات مستحقة", name_en: "بدلات وتعويضات مستحقة", type: "liability", level: "detail", parent: "2120", desc: "البدلات والتعويضات المستحقة" },
  { code: "2130", name_ar: "الالتزامات الضريبية", name_en: "الالتزامات الضريبية", type: "liability", level: "group", parent: "2100", desc: "الضرائب والرسوم المستحقة الدفع" },
  { code: "2131", name_ar: "ضريبة القيمة المضافة مستحقة", name_en: "ضريبة القيمة المضافة مستحقة", type: "liability", level: "detail", parent: "2130", desc: "ضريبة القيمة المضافة المستحقة للهيئة" },
  { code: "2132", name_ar: "ضريبة الدخل والزكاة مستحقة", name_en: "ضريبة الدخل والزكاة مستحقة", type: "liability", level: "detail", parent: "2130", desc: "ضريبة الدخل والزكاة المستحقة" },
  { code: "2133", name_ar: "رسوم وتراخيص مستحقة", name_en: "رسوم وتراخيص مستحقة", type: "liability", level: "detail", parent: "2130", desc: "الرسوم والتراخيص المستحقة للجهات الحكومية" },
  { code: "2140", name_ar: "القروض والتمويلات قصيرة الأجل", name_en: "القروض والتمويلات قصيرة الأجل", type: "liability", level: "group", parent: "2100", desc: "القروض المستحقة الدفع خلال سنة" },
  { code: "2141", name_ar: "قرض بنكي قصير الأجل - البنك الأول", name_en: "قرض بنكي قصير الأجل - البنك الأول", type: "liability", level: "detail", parent: "2140", desc: "القرض المستحق من البنك الأول" },
  { code: "2142", name_ar: "قرض بنكي قصير الأجل - البنك الثاني", name_en: "قرض بنكي قصير الأجل - البنك الثاني", type: "liability", level: "detail", parent: "2140", desc: "القرض المستحق من البنك الثاني" },
  { code: "2150", name_ar: "الفوائد المستحقة", name_en: "الفوائد المستحقة", type: "liability", level: "detail", parent: "2100", desc: "الفوائد على القروض والتمويلات" },
  { code: "2200", name_ar: "الالتزامات طويلة الأجل", name_en: "الالتزامات طويلة الأجل", type: "liability", level: "group", parent: "2000", desc: "الالتزامات المستحقة الدفع بعد سنة" },
  { code: "2210", name_ar: "القروض طويلة الأجل", name_en: "القروض طويلة الأجل", type: "liability", level: "group", parent: "2200", desc: "القروض المستحقة على فترة طويلة" },
  { code: "2211", name_ar: "قرض بنكي طويل الأجل - البنك الأول", name_en: "قرض بنكي طويل الأجل - البنك الأول", type: "liability", level: "detail", parent: "2210", desc: "القرض الحكومي طويل الأجل" },
  { code: "2212", name_ar: "قرض بنكي طويل الأجل - البنك الثاني", name_en: "قرض بنكي طويل الأجل - البنك الثاني", type: "liability", level: "detail", parent: "2210", desc: "القرض التجاري طويل الأجل" },
  { code: "2220", name_ar: "الالتزامات أخرى طويلة الأجل", name_en: "الالتزامات أخرى طويلة الأجل", type: "liability", level: "detail", parent: "2200", desc: "التزامات أخرى طويلة الأجل" },
  { code: "3000", name_ar: "حقوق الملكية", name_en: "حقوق الملكية", type: "equity", level: "root", desc: "حقوق الملاك والاحتياطيات والأرباح" },
  { code: "3100", name_ar: "رأس المال والاحتياطيات", name_en: "رأس المال والاحتياطيات", type: "equity", level: "group", parent: "3000", desc: "رأس المال المدفوع والاحتياطيات" },
  { code: "3101", name_ar: "رأس المال المدفوع", name_en: "رأس المال المدفوع", type: "equity", level: "detail", parent: "3100", desc: "رأس المال المدفوع من قبل المالكين" },
  { code: "3102", name_ar: "احتياطي قانوني", name_en: "احتياطي قانوني", type: "equity", level: "detail", parent: "3100", desc: "الاحتياطي القانوني المكتسب من الأرباح" },
  { code: "3103", name_ar: "احتياطيات اختيارية", name_en: "احتياطيات اختيارية", type: "equity", level: "detail", parent: "3100", desc: "احتياطيات اختيارية أخرى" },
  { code: "3200", name_ar: "الأرباح المحتجزة والخسائر", name_en: "الأرباح المحتجزة والخسائر", type: "equity", level: "group", parent: "3000", desc: "الأرباح من السنوات السابقة" },
  { code: "3201", name_ar: "الأرباح المحتجزة - سنوات سابقة", name_en: "الأرباح المحتجزة - سنوات سابقة", type: "equity", level: "detail", parent: "3200", desc: "الأرباح المحتجزة من السنوات السابقة" },
  { code: "3202", name_ar: "الأرباح/(الخسائر) للسنة المالية الحالية", name_en: "الأرباح/(الخسائر) للسنة المالية الحالية", type: "equity", level: "detail", parent: "3200", desc: "الربح أو الخسارة للسنة الحالية" },
  { code: "4000", name_ar: "إيرادات الخدمات الطبية", name_en: "إيرادات الخدمات الطبية", type: "revenue", level: "root", desc: "إجمالي إيرادات الخدمات الطبية" },
  { code: "4100", name_ar: "إيرادات الكشوفات والفحوصات", name_en: "إيرادات الكشوفات والفحوصات", type: "revenue", level: "group", parent: "4000", desc: "الكشوفات والفحوصات الطبية" },
  { code: "4110", name_ar: "إيرادات كشوفات الطبيب الأول", name_en: "إيرادات كشوفات الطبيب الأول", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات كشوفات الطبيب الأول" },
  { code: "4111", name_ar: "إيرادات كشوفات الطبيب الثاني", name_en: "إيرادات كشوفات الطبيب الثاني", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات كشوفات الطبيب الثاني" },
  { code: "4112", name_ar: "إيرادات كشوفات الطبيب الثالث", name_en: "إيرادات كشوفات الطبيب الثالث", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات كشوفات الطبيب الثالث" },
  { code: "4113", name_ar: "إيرادات كشوفات الطبيب الرابع", name_en: "إيرادات كشوفات الطبيب الرابع", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات كشوفات الطبيب الرابع" },
  { code: "4114", name_ar: "إيرادات كشوفات الطبيب الخامس", name_en: "إيرادات كشوفات الطبيب الخامس", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات كشوفات الطبيب الخامس" },
  { code: "4115", name_ar: "إيرادات كشوفات - طاقم تمريض", name_en: "إيرادات كشوفات - طاقم تمريض", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات كشوفات طاقم التمريض" },
  { code: "4116", name_ar: "إيرادات كشوفات - استشارات خارجية", name_en: "إيرادات كشوفات - استشارات خارجية", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات الاستشارات من أطباء خارجيين" },
  { code: "4120", name_ar: "إيرادات الفحوصات المخبرية", name_en: "إيرادات الفحوصات المخبرية", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات التحاليل والفحوصات المخبرية" },
  { code: "4130", name_ar: "إيرادات الأشعات والتصوير الطبي", name_en: "إيرادات الأشعات والتصوير الطبي", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات خدمات التصوير الطبي" },
  { code: "4140", name_ar: "إيرادات الجراحات والعمليات", name_en: "إيرادات الجراحات والعمليات", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات الجراحات والعمليات الطبية" },
  { code: "4150", name_ar: "إيرادات الخدمات الطبية الأخرى", name_en: "إيرادات الخدمات الطبية الأخرى", type: "revenue", level: "detail", parent: "4100", desc: "إيرادات خدمات طبية متنوعة" },
  { code: "4200", name_ar: "إيرادات بيع الأدوية والمستهلكات", name_en: "إيرادات بيع الأدوية والمستهلكات", type: "revenue", level: "detail", parent: "4000", desc: "إيرادات بيع الأدوية والمستهلكات" },
  { code: "4300", name_ar: "إيرادات أخرى", name_en: "إيرادات أخرى", type: "revenue", level: "detail", parent: "4000", desc: "إيرادات متنوعة أخرى" },
  { code: "5000", name_ar: "تكاليف الخدمات الطبية والإدارية", name_en: "تكاليف الخدمات الطبية والإدارية", type: "expense", level: "root", desc: "إجمالي تكاليف تقديم الخدمات" },
  { code: "5100", name_ar: "رواتب وأجور الأطباء", name_en: "رواتب وأجور الأطباء", type: "expense", level: "group", parent: "5000", desc: "رواتب وأجور الأطباء" },
  { code: "5110", name_ar: "راتب الطبيب الأول", name_en: "راتب الطبيب الأول", type: "expense", level: "detail", parent: "5100", desc: "راتب الطبيب الأول الشهري" },
  { code: "5111", name_ar: "راتب الطبيب الثاني", name_en: "راتب الطبيب الثاني", type: "expense", level: "detail", parent: "5100", desc: "راتب الطبيب الثاني الشهري" },
  { code: "5112", name_ar: "راتب الطبيب الثالث", name_en: "راتب الطبيب الثالث", type: "expense", level: "detail", parent: "5100", desc: "راتب الطبيب الثالث الشهري" },
  { code: "5113", name_ar: "راتب الطبيب الرابع", name_en: "راتب الطبيب الرابع", type: "expense", level: "detail", parent: "5100", desc: "راتب الطبيب الرابع الشهري" },
  { code: "5114", name_ar: "راتب الطبيب الخامس", name_en: "راتب الطبيب الخامس", type: "expense", level: "detail", parent: "5100", desc: "راتب الطبيب الخامس الشهري" },
  { code: "5120", name_ar: "عمولات وحوافز الطبيب الأول", name_en: "عمولات وحوافز الطبيب الأول", type: "expense", level: "detail", parent: "5100", desc: "عمولات الطبيب الأول عن الإجراءات الإضافية" },
  { code: "5121", name_ar: "عمولات وحوافز الطبيب الثاني", name_en: "عمولات وحوافز الطبيب الثاني", type: "expense", level: "detail", parent: "5100", desc: "عمولات الطبيب الثاني عن الإجراءات الإضافية" },
  { code: "5122", name_ar: "عمولات وحوافز الطبيب الثالث", name_en: "عمولات وحوافز الطبيب الثالث", type: "expense", level: "detail", parent: "5100", desc: "عمولات الطبيب الثالث عن الإجراءات الإضافية" },
  { code: "5123", name_ar: "عمولات وحوافز الطبيب الرابع", name_en: "عمولات وحوافز الطبيب الرابع", type: "expense", level: "detail", parent: "5100", desc: "عمولات الطبيب الرابع عن الإجراءات الإضافية" },
  { code: "5124", name_ar: "عمولات وحوافز الطبيب الخامس", name_en: "عمولات وحوافز الطبيب الخامس", type: "expense", level: "detail", parent: "5100", desc: "عمولات الطبيب الخامس عن الإجراءات الإضافية" },
  { code: "5200", name_ar: "رواتب وأجور طاقم التمريض والمساعدين", name_en: "رواتب وأجور طاقم التمريض والمساعدين", type: "expense", level: "group", parent: "5000", desc: "رواتب طاقم التمريض والمساعدين" },
  { code: "5210", name_ar: "رواتب فريق التمريض", name_en: "رواتب فريق التمريض", type: "expense", level: "detail", parent: "5200", desc: "رواتب فريق التمريض" },
  { code: "5220", name_ar: "رواتب المساعدين الطبيين", name_en: "رواتب المساعدين الطبيين", type: "expense", level: "detail", parent: "5200", desc: "رواتب المساعدين الطبيين والفنيين" },
  { code: "5230", name_ar: "رواتب عمال التنظيف الطبي", name_en: "رواتب عمال التنظيف الطبي", type: "expense", level: "detail", parent: "5200", desc: "رواتب عمال التنظيف والعقيمة" },
  { code: "5300", name_ar: "أدوات وأجهزة الطبيب الأول", name_en: "أدوات وأجهزة الطبيب الأول", type: "expense", level: "detail", parent: "5000", desc: "أدوات وأجهزة الطبيب الأول" },
  { code: "5301", name_ar: "أدوات وأجهزة الطبيب الثاني", name_en: "أدوات وأجهزة الطبيب الثاني", type: "expense", level: "detail", parent: "5000", desc: "أدوات وأجهزة الطبيب الثاني" },
  { code: "5302", name_ar: "أدوات وأجهزة الطبيب الثالث", name_en: "أدوات وأجهزة الطبيب الثالث", type: "expense", level: "detail", parent: "5000", desc: "أدوات وأجهزة الطبيب الثالث" },
  { code: "5303", name_ar: "أدوات وأجهزة الطبيب الرابع", name_en: "أدوات وأجهزة الطبيب الرابع", type: "expense", level: "detail", parent: "5000", desc: "أدوات وأجهزة الطبيب الرابع" },
  { code: "5304", name_ar: "أدوات وأجهزة الطبيب الخامس", name_en: "أدوات وأجهزة الطبيب الخامس", type: "expense", level: "detail", parent: "5000", desc: "أدوات وأجهزة الطبيب الخامس" },
  { code: "5400", name_ar: "المستهلكات الطبية العامة", name_en: "المستهلكات الطبية العامة", type: "expense", level: "group", parent: "5000", desc: "المستهلكات الطبية المختلفة" },
  { code: "5410", name_ar: "الأدوية والعقاقير", name_en: "الأدوية والعقاقير", type: "expense", level: "detail", parent: "5400", desc: "شراء الأدوية والعقاقير الطبية" },
  { code: "5420", name_ar: "المستهلكات الطبية (إبر - قطن - شاش)", name_en: "المستهلكات الطبية (إبر - قطن - شاش)", type: "expense", level: "detail", parent: "5400", desc: "المستهلكات الطبية المتنوعة" },
  { code: "5430", name_ar: "مستهلكات التنظيف والتعقيم", name_en: "مستهلكات التنظيف والتعقيم", type: "expense", level: "detail", parent: "5400", desc: "مستهلكات التنظيف والتطهير" },
  { code: "5500", name_ar: "صيانة وإصلاح المعدات الطبية", name_en: "صيانة وإصلاح المعدات الطبية", type: "expense", level: "group", parent: "5000", desc: "تكاليف صيانة المعدات الطبية" },
  { code: "5510", name_ar: "صيانة أجهزة الأشعات والمعدات الثقيلة", name_en: "صيانة أجهزة الأشعات والمعدات الثقيلة", type: "expense", level: "detail", parent: "5500", desc: "صيانة الأجهزة الطبية الثقيلة" },
  { code: "5520", name_ar: "صيانة المعدات الطبية العامة", name_en: "صيانة المعدات الطبية العامة", type: "expense", level: "detail", parent: "5500", desc: "صيانة المعدات الطبية الأخرى" },
  { code: "5530", name_ar: "قطع الغيار والملحقات للمعدات", name_en: "قطع الغيار والملحقات للمعدات", type: "expense", level: "detail", parent: "5500", desc: "قطع الغيار والملحقات" },
  { code: "5600", name_ar: "تكاليف المرافق والخدمات العامة", name_en: "تكاليف المرافق والخدمات العامة", type: "expense", level: "group", parent: "5000", desc: "تكاليف المرافق والخدمات" },
  { code: "5610", name_ar: "فاتورة الكهرباء والمياه", name_en: "فاتورة الكهرباء والمياه", type: "expense", level: "detail", parent: "5600", desc: "فاتورة الكهرباء والمياه الشهرية" },
  { code: "5620", name_ar: "فاتورة الغاز والوقود", name_en: "فاتورة الغاز والوقود", type: "expense", level: "detail", parent: "5600", desc: "تكاليف الغاز والوقود" },
  { code: "5630", name_ar: "فاتورة الهاتف والإنترنت", name_en: "فاتورة الهاتف والإنترنت", type: "expense", level: "detail", parent: "5600", desc: "فاتورة الهاتف والإنترنت" },
  { code: "5640", name_ar: "تكاليف إيجار المبنى", name_en: "تكاليف إيجار المبنى", type: "expense", level: "detail", parent: "5600", desc: "رسوم إيجار المبنى الشهري" },
  { code: "5650", name_ar: "تكاليف الأمن والحراسة", name_en: "تكاليف الأمن والحراسة", type: "expense", level: "detail", parent: "5600", desc: "رسوم خدمات الأمن والحراسة" },
  { code: "5660", name_ar: "تكاليف التنظيف والنظافة", name_en: "تكاليف التنظيف والنظافة", type: "expense", level: "detail", parent: "5600", desc: "تكاليف التنظيف اليومي والنظافة" },
  { code: "5670", name_ar: "تأمين المبنى والمحتويات", name_en: "تأمين المبنى والمحتويات", type: "expense", level: "detail", parent: "5600", desc: "بوليصة التأمين على المبنى والمحتويات" },
  { code: "5700", name_ar: "رواتب الموظفين الإداريين", name_en: "رواتب الموظفين الإداريين", type: "expense", level: "group", parent: "5000", desc: "رواتب الموظفين الإداريين" },
  { code: "5710", name_ar: "راتب مدير المركز", name_en: "راتب مدير المركز", type: "expense", level: "detail", parent: "5700", desc: "راتب مدير المركز الطبي" },
  { code: "5720", name_ar: "راتب المحاسب والموظفين الماليين", name_en: "راتب المحاسب والموظفين الماليين", type: "expense", level: "detail", parent: "5700", desc: "راتب المحاسب وموظفي المالية" },
  { code: "5730", name_ar: "راتب موظفي الاستقبال والإدارة", name_en: "راتب موظفي الاستقبال والإدارة", type: "expense", level: "detail", parent: "5700", desc: "رواتب موظفي الاستقبال" },
  { code: "5740", name_ar: "راتب مدير الموارد البشرية", name_en: "راتب مدير الموارد البشرية", type: "expense", level: "detail", parent: "5700", desc: "راتب مدير الموارد البشرية" },
  { code: "5800", name_ar: "المصروفات الإدارية والعامة", name_en: "المصروفات الإدارية والعامة", type: "expense", level: "group", parent: "5000", desc: "المصروفات الإدارية والعامة" },
  { code: "5810", name_ar: "رسوم المحاسبة والمراجعة والاستشارات", name_en: "رسوم المحاسبة والمراجعة والاستشارات", type: "expense", level: "detail", parent: "5800", desc: "رسوم المحاسبين والمستشارين" },
  { code: "5820", name_ar: "رسوم الاستشارات القانونية", name_en: "رسوم الاستشارات القانونية", type: "expense", level: "detail", parent: "5800", desc: "رسوم الاستشارات القانونية" },
  { code: "5830", name_ar: "الرسوم والتراخيص الحكومية", name_en: "الرسوم والتراخيص الحكومية", type: "expense", level: "detail", parent: "5800", desc: "رسوم التراخيص الحكومية والطبية" },
  { code: "5840", name_ar: "تكاليف الإعلان والعلاقات العامة", name_en: "تكاليف الإعلان والعلاقات العامة", type: "expense", level: "detail", parent: "5800", desc: "تكاليف الإعلان والتسويق" },
  { code: "5850", name_ar: "تكاليف التدريب والتطوير الموظفين", name_en: "تكاليف التدريب والتطوير الموظفين", type: "expense", level: "detail", parent: "5800", desc: "تكاليف التدريب والتطوير" },
  { code: "5860", name_ar: "المساهمات والعضويات المهنية", name_en: "المساهمات والعضويات المهنية", type: "expense", level: "detail", parent: "5800", desc: "المساهمات والعضويات المهنية" },
  { code: "5870", name_ar: "تكاليف السفر والمشاركات العلمية", name_en: "تكاليف السفر والمشاركات العلمية", type: "expense", level: "detail", parent: "5800", desc: "تكاليف السفر والمؤتمرات" },
  { code: "5880", name_ar: "المكتبة والمراجع الطبية", name_en: "المكتبة والمراجع الطبية", type: "expense", level: "detail", parent: "5800", desc: "شراء الكتب والمراجع الطبية" },
  { code: "5890", name_ar: "تكاليف إدارية وعامة أخرى", name_en: "تكاليف إدارية وعامة أخرى", type: "expense", level: "detail", parent: "5800", desc: "تكاليف إدارية وعامة متنوعة" },
  { code: "5900", name_ar: "التأمينات الاجتماعية والموارد البشرية", name_en: "التأمينات الاجتماعية والموارد البشرية", type: "expense", level: "group", parent: "5000", desc: "التأمينات والموارد البشرية" },
  { code: "5910", name_ar: "المساهمات في التأمينات الاجتماعية", name_en: "المساهمات في التأمينات الاجتماعية", type: "expense", level: "detail", parent: "5900", desc: "المساهمات في التأمينات الاجتماعية" },
  { code: "5920", name_ar: "التأمين الصحي للموظفين", name_en: "التأمين الصحي للموظفين", type: "expense", level: "detail", parent: "5900", desc: "التأمين الصحي لموظفي المركز" },
  { code: "5930", name_ar: "بدلات ومكافآت الموظفين", name_en: "بدلات ومكافآت الموظفين", type: "expense", level: "detail", parent: "5900", desc: "بدلات ومكافآت الموظفين" },
  { code: "6000", name_ar: "الإيرادات الأخرى والمصروفات الأخرى", name_en: "الإيرادات الأخرى والمصروفات الأخرى", type: "expense", level: "root", desc: "الإيرادات والمصروفات الأخرى" },
  { code: "6100", name_ar: "الإيرادات الأخرى", name_en: "الإيرادات الأخرى", type: "revenue", level: "detail", parent: "6000", desc: "إيرادات متنوعة أخرى" },
  { code: "6200", name_ar: "المصروفات الأخرى", name_en: "المصروفات الأخرى", type: "expense", level: "detail", parent: "6000", desc: "مصروفات متنوعة أخرى" },
  { code: "6300", name_ar: "الخسائر والديون المعدومة", name_en: "الخسائر والديون المعدومة", type: "expense", level: "detail", parent: "6000", desc: "خسائر الديون المعدومة" },
  { code: "6400", name_ar: "فروقات الصرف العملات الأجنبية", name_en: "فروقات الصرف العملات الأجنبية", type: "expense", level: "detail", parent: "6000", desc: "فروقات الصرف والعملات" },
];