import {
  Stethoscope, Users, Package, ShoppingCart, Receipt, Headset,
  Building2, Wrench, Car, Wallet, Landmark, BookOpen, FolderKanban,
  ShieldCheck, MessageSquare, Archive, Settings, Activity,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type SubItem = { slug: string; en: string; ar: string };
export type ModuleDef = {
  slug: string;
  en: string;
  ar: string;
  icon: LucideIcon;
  desc_en: string;
  desc_ar: string;
  items: SubItem[];
};

export const MODULES: ModuleDef[] = [
  {
    slug: "journey", en: "Patient Journey", ar: "رحلة المريض", icon: Activity,
    desc_en: "Patient Cases, services, invoices, payments, radiology, inventory, batches",
    desc_ar: "حالات المرضى والخدمات والفواتير والمدفوعات والأشعة والمواد والدفعات المحاسبية",
    items: [
      { slug: "reception-dash", en: "Reception Dashboard", ar: "لوحة الاستقبال" },
      { slug: "doctor-dash", en: "Doctor Dashboard", ar: "لوحة الطبيب" },
      { slug: "patients", en: "Patients", ar: "المرضى" },
      { slug: "cases", en: "Patient Cases", ar: "حالات المرضى" },
      { slug: "services", en: "Services & Price List", ar: "الخدمات والأسعار" },
      { slug: "invoices", en: "Invoices", ar: "الفواتير" },
      { slug: "payments", en: "Payments", ar: "المدفوعات" },
      { slug: "radiology", en: "Radiology Center", ar: "قسم الأشعة" },
      { slug: "packets", en: "Tools & Packets", ar: "الأطقم والأدوات" },
      { slug: "materials", en: "Material Requests", ar: "طلبات المواد" },
      { slug: "batches", en: "Accounting Batches", ar: "الدفعات المحاسبية" },
      { slug: "profitability", en: "Doctor Profitability", ar: "ربحية الأطباء" },
      { slug: "activity", en: "Activity Log", ar: "سجل النشاط" },
    ],
  },
  {
    slug: "medical", en: "Medical Systems", ar: "الأنظمة الطبية", icon: Stethoscope,
    desc_en: "Patients, clinics, inpatient, labs, radiology, surgery, billing",
    desc_ar: "المرضى والعيادات والتنويم والمختبرات والأشعة والعمليات والفواتير",
    items: [
      { slug: "patient-search", en: "Patient Search", ar: "بحث المرضى" },
      { slug: "clinic-booking", en: "Clinic Booking", ar: "حجز العيادات" },
      { slug: "clinic-reception", en: "Clinic Reception", ar: "استقبال العيادات" },
      { slug: "clinic-management", en: "Clinic Management", ar: "إدارة العيادات" },
      { slug: "lab-results", en: "Lab Results", ar: "نتائج المختبر" },
      { slug: "radiology", en: "Radiology", ar: "الأشعة" },
      { slug: "pending-invoices", en: "Pending Patient Invoices", ar: "فواتير المرضى المعلقة" },
      { slug: "emergency", en: "Emergency Management", ar: "إدارة الطوارئ" },
      { slug: "surgery", en: "Operations & Surgery", ar: "العمليات والجراحة" },
      { slug: "cafeteria", en: "Cafeteria & Kitchen", ar: "الكافتيريا والمطبخ" },
      { slug: "doctor-schedules", en: "Doctor Schedules", ar: "جداول الأطباء" },
      { slug: "nursing", en: "Nursing Management", ar: "إدارة التمريض" },
      { slug: "inpatient-rounds", en: "Inpatient Rounds", ar: "جولات التنويم" },
      { slug: "outpatient-billing", en: "Outpatient Billing", ar: "فواتير العيادات الخارجية" },
      { slug: "inpatient-billing", en: "Inpatient Billing", ar: "فواتير التنويم" },
      { slug: "insurance-claims", en: "Insurance Claims", ar: "مطالبات التأمين" },
      { slug: "home-care", en: "Home Care", ar: "الرعاية المنزلية" },
      { slug: "medical-records", en: "Medical Records", ar: "السجلات الطبية" },
      { slug: "jci", en: "JCI Compliance", ar: "الاعتماد الدولي JCI" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "hr", en: "HR Management", ar: "إدارة الموارد البشرية", icon: Users,
    desc_en: "Employees, payroll, attendance, leave, recruitment, training",
    desc_ar: "الموظفون والرواتب والحضور والإجازات والتوظيف والتدريب",
    items: [
      { slug: "org-structure", en: "Org Structure", ar: "الهيكل الوظيفي" },
      { slug: "employees", en: "Employees", ar: "الموظفون" },
      { slug: "payroll", en: "Payroll", ar: "الرواتب" },
      { slug: "attendance", en: "Attendance", ar: "الحضور والانصراف" },
      { slug: "vacations", en: "Vacations", ar: "الإجازات" },
      { slug: "deductions", en: "Deductions & Bonuses", ar: "الخصومات والمكافآت" },
      { slug: "advances", en: "Salary Advances", ar: "السلف" },
      { slug: "recruitment", en: "Recruitment", ar: "التوظيف" },
      { slug: "training", en: "Training", ar: "التدريب" },
      { slug: "roster", en: "Staff Roster", ar: "جدول العمل" },
      { slug: "nursing-shifts", en: "Nursing Shifts", ar: "ورديات التمريض" },
      { slug: "self-service", en: "Employee Self-Service", ar: "الخدمة الذاتية للموظف" },
      { slug: "labor-law", en: "Labor Law", ar: "قانون العمل" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "inventory", en: "Items & Inventory", ar: "الأصناف والمخزون", icon: Package,
    desc_en: "Items, barcodes, stock movements, warehouses, pharmacy",
    desc_ar: "الأصناف والباركود وحركة المخزون والمستودعات والصيدلية",
    items: [
      { slug: "medicine-dispensing", en: "Medicine Dispensing", ar: "صرف الأدوية" },
      { slug: "items", en: "Items", ar: "الأصناف" },
      { slug: "barcode", en: "Barcode Printing", ar: "طباعة الباركود" },
      { slug: "stock-in", en: "Stock-In Permits", ar: "أذونات الإدخال" },
      { slug: "stock-out", en: "Stock-Out Permits", ar: "أذونات الإخراج" },
      { slug: "returns", en: "Return Permits", ar: "أذونات الإرجاع" },
      { slug: "receiving", en: "Receiving & Inspection", ar: "الاستلام والفحص" },
      { slug: "approvals", en: "Approvals", ar: "الموافقات" },
      { slug: "warehouse-monitor", en: "Warehouse Monitor", ar: "مراقبة المستودع" },
      { slug: "warehouses", en: "Warehouses", ar: "المستودعات" },
      { slug: "pharmacy", en: "Clinical Pharmacy", ar: "الصيدلية الإكلينيكية" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "purchases", en: "Purchases & Suppliers", ar: "المشتريات والموردين", icon: ShoppingCart,
    desc_en: "RFQs, POs, supplier invoices, returns, expenses",
    desc_ar: "طلبات الشراء وأوامر الشراء وفواتير الموردين والمرتجعات والمصروفات",
    items: [
      { slug: "requests", en: "Purchase Requests (PR)", ar: "طلبات الشراء (PR)" },
      { slug: "offers", en: "Supplier Offers (RFQ)", ar: "عروض الموردين (RFQ)" },
      { slug: "orders", en: "Purchase Orders (PO)", ar: "أوامر الشراء (PO)" },
      { slug: "goods-receipts", en: "Goods Receipts (GR)", ar: "إيصالات الاستلام (GR)" },
      { slug: "invoices", en: "Vendor Invoices (VI)", ar: "فواتير الموردين (VI)" },
      { slug: "return-invoices", en: "Credit Notes (CN)", ar: "إشعارات دائنة (CN)" },
      { slug: "taxes", en: "Discounts & Taxes", ar: "الخصومات والضرائب" },
      { slug: "expenses", en: "Direct Expenses", ar: "المصروفات المباشرة" },
      { slug: "planning", en: "Purchase Planning", ar: "تخطيط المشتريات" },
      { slug: "approvals", en: "Purchase Approvals", ar: "موافقات الشراء" },
      { slug: "suppliers", en: "Suppliers", ar: "الموردون" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "sales", en: "Sales & Customers", ar: "المبيعات والعملاء", icon: Receipt,
    desc_en: "Invoices, POS, restaurant, pharmacy, CRM, subscriptions",
    desc_ar: "الفواتير ونقاط البيع والمطعم والصيدلية والعملاء والاشتراكات",
    items: [
      { slug: "new-invoice", en: "New Sales Invoice", ar: "فاتورة بيع جديدة" },
      { slug: "returns", en: "Sales Returns", ar: "مرتجعات البيع" },
      { slug: "pos", en: "Point of Sale", ar: "نقطة البيع" },
      { slug: "restaurant", en: "Restaurant POS", ar: "نقطة بيع المطعم" },
      { slug: "pharmacy-pos", en: "Pharmacy POS", ar: "نقطة بيع الصيدلية" },
      { slug: "handover", en: "Cashier Handover", ar: "تسليم الكاشير" },
      { slug: "invoices", en: "Sales Invoices", ar: "فواتير البيع" },
      { slug: "agreements", en: "Agreements", ar: "الاتفاقيات" },
      { slug: "shipping", en: "Shipping", ar: "الشحن" },
      { slug: "claims", en: "Customer Claims", ar: "مطالبات العملاء" },
      { slug: "bnpl-claims", en: "BNPL Claims (Tabby/Tamara)", ar: "مطالبات Tabby / Tamara" },
      { slug: "website", en: "Website", ar: "إدارة الموقع" },
      { slug: "surveys", en: "Surveys", ar: "الاستبيانات" },
      { slug: "subscriptions", en: "Subscriptions", ar: "الاشتراكات" },
      { slug: "leads", en: "Leads (CRM)", ar: "العملاء المحتملون" },
      { slug: "customers", en: "Customers", ar: "العملاء" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "services", en: "Services & Tickets", ar: "العملاء والخدمات", icon: Headset,
    desc_en: "Helpdesk, tickets, service renewals",
    desc_ar: "الدعم الفني والتذاكر وتجديد الخدمات",
    items: [
      { slug: "customers", en: "Customer Data", ar: "بيانات العملاء" },
      { slug: "open-services", en: "Open Services", ar: "الخدمات المفتوحة" },
      { slug: "open-tickets", en: "Open Tickets", ar: "التذاكر المفتوحة" },
      { slug: "renewals", en: "Renewals", ar: "التجديدات" },
      { slug: "closed-services", en: "Closed Services", ar: "الخدمات المغلقة" },
      { slug: "closed-tickets", en: "Closed Tickets", ar: "التذاكر المغلقة" },
      { slug: "new-ticket", en: "New Ticket", ar: "تذكرة جديدة" },
    ],
  },
  {
    slug: "assets", en: "Fixed Assets", ar: "الأصول الثابتة", icon: Building2,
    desc_en: "Assets, depreciation, registry",
    desc_ar: "الأصول والاستهلاك والسجل",
    items: [
      { slug: "add", en: "Add Asset", ar: "إضافة أصل" },
      { slug: "depreciation", en: "Depreciation", ar: "الاستهلاك" },
      { slug: "list", en: "Assets List", ar: "قائمة الأصول" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "maintenance", en: "Maintenance", ar: "مراكز الصيانة", icon: Wrench,
    desc_en: "Work orders and equipment",
    desc_ar: "أوامر العمل والمعدات",
    items: [
      { slug: "work-orders", en: "Work Orders", ar: "أوامر العمل" },
      { slug: "machines", en: "Machines", ar: "الآلات" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "fleet", en: "Fleet & Vehicles", ar: "السيارات والمركبات", icon: Car,
    desc_en: "Ambulances, rentals, movements",
    desc_ar: "سيارات الإسعاف والتأجير والحركات",
    items: [
      { slug: "ambulance", en: "Ambulance Requests", ar: "طلبات الإسعاف" },
      { slug: "cars", en: "Cars", ar: "السيارات" },
      { slug: "rental", en: "Rental Contracts", ar: "عقود التأجير" },
      { slug: "movements", en: "Movement Data", ar: "بيانات الحركة" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "cash", en: "Cash & Treasury", ar: "النقدية", icon: Wallet,
    desc_en: "Vouchers, custody, transfers",
    desc_ar: "السندات والعهد والتحويلات",
    items: [
      { slug: "reception-shift", en: "Reception Shift", ar: "خزينة الاستقبال" },
      { slug: "treasury-approval", en: "Treasury Approval", ar: "اعتماد الخزينة" },
      { slug: "vouchers", en: "Cash Vouchers", ar: "سندات الصرف" },
      { slug: "custody", en: "Employee Custody", ar: "عهدة الموظفين" },
      { slug: "supplier-payments", en: "Supplier Payments", ar: "دفعات الموردين" },
      { slug: "approvals", en: "Approvals", ar: "الموافقات" },
      { slug: "receivable", en: "Receivable Vouchers", ar: "سندات القبض" },
      { slug: "payable", en: "Payable Vouchers", ar: "سندات الدفع" },
      { slug: "transfers", en: "Transfers", ar: "التحويلات" },
      { slug: "balance", en: "Treasury Balance", ar: "رصيد الخزينة" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "banks", en: "Banks", ar: "البنوك", icon: Landmark,
    desc_en: "Checks, loans, deposits, guarantees, transfers",
    desc_ar: "الشيكات والقروض والودائع والكفالات والتحويلات",
    items: [
      { slug: "bank-list", en: "Bank List", ar: "قائمة البنوك" },
      { slug: "bank-txns", en: "Bank Transactions", ar: "حركات البنك" },
      { slug: "reconciliation", en: "Reconciliation Dashboard", ar: "لوحة التسوية البنكية" },
      { slug: "unreconciled", en: "Unreconciled Transactions", ar: "الحركات غير المسوّاة" },
      { slug: "statement-import", en: "Statement Import", ar: "استيراد كشف البنك" },
      { slug: "settlements", en: "Settlement History", ar: "سجل التسويات" },
      { slug: "approvals", en: "Reconciliation Approval", ar: "اعتماد التسويات" },
      { slug: "check-requests", en: "Check Requests", ar: "طلبات شيكات" },
      { slug: "check-orders", en: "Check Orders", ar: "أوامر شيكات" },
      { slug: "issuance", en: "Check Issuance", ar: "إصدار الشيكات" },
      { slug: "income", en: "Bank Income/Expenses", ar: "مداخيل ومصاريف البنك" },
      { slug: "loans", en: "Loans", ar: "القروض" },
      { slug: "deposits", en: "Deposits", ar: "الودائع" },
      { slug: "guarantees", en: "Letters of Guarantee", ar: "خطابات الضمان" },
      { slug: "issued", en: "Issued Checks", ar: "الشيكات المصدرة" },
      { slug: "received", en: "Received Checks", ar: "الشيكات المستلمة" },
      { slug: "transfers", en: "Inter-bank Transfers", ar: "التحويلات بين البنوك" },
      { slug: "balances", en: "Bank Balances", ar: "أرصدة البنوك" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "accounting", en: "General Accounting", ar: "الحسابات العامة", icon: BookOpen,
    desc_en: "Journals, ledger, trial balance, financials",
    desc_ar: "القيود ودفتر الأستاذ وميزان المراجعة والقوائم المالية",
    items: [
      { slug: "erp-dashboard", en: "ERP Dashboard", ar: "لوحة تحكم النظام" },
      { slug: "kpis", en: "Realtime KPIs", ar: "مؤشرات الأداء الحية" },
      { slug: "posting-rules", en: "Posting Rules", ar: "قواعد الترحيل" },
      { slug: "chart-of-accounts", en: "Chart of Accounts", ar: "دليل الحسابات" },
      { slug: "journal", en: "Journal Entries", ar: "القيود اليومية" },
      { slug: "ledger", en: "General Ledger", ar: "دفتر الأستاذ" },
      { slug: "cost-centers", en: "Cost Centers", ar: "مراكز التكلفة" },
      { slug: "org-structure", en: "Org Structure & Centers", ar: "الهيكل الوظيفي ومراكز التكلفة والربحية" },
      { slug: "profit-centers", en: "Profit Centers", ar: "مراكز الربحية" },
      { slug: "cost-distribution", en: "Cost Distribution", ar: "توزيع التكاليف" },
      { slug: "clinic-profitability", en: "Clinic Profitability", ar: "ربحية العيادات" },
      { slug: "financial-statements", en: "Financial Statements", ar: "القوائم المالية" },
      { slug: "customer-ledger", en: "Customer Ledger", ar: "كشف حساب العملاء" },
      { slug: "account-movements", en: "Account Movements", ar: "حركات الحساب" },
      { slug: "statement", en: "Account Statement", ar: "كشف حساب" },
      { slug: "trial-balance", en: "Trial Balance", ar: "ميزان المراجعة" },
      { slug: "income-statement", en: "Income Statement", ar: "قائمة الدخل" },
      { slug: "balance-sheet", en: "Balance Sheet", ar: "الميزانية" },
      { slug: "budget", en: "Budget", ar: "الموازنة" },
      { slug: "final-accounts", en: "Period Close & Year-End", ar: "إقفال الفترات والسنة" },
      { slug: "period-close", en: "Period Close", ar: "إقفال الفترة" },
      { slug: "e-invoicing", en: "E-Invoicing", ar: "الفوترة الإلكترونية" },
      { slug: "designer", en: "Statements Designer", ar: "مصمم القوائم" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "projects", en: "Projects & Tasks", ar: "المشاريع والمهام", icon: FolderKanban,
    desc_en: "Plan and track projects and tasks",
    desc_ar: "تخطيط ومتابعة المشاريع والمهام",
    items: [
      { slug: "new", en: "New Task / Project", ar: "مهمة / مشروع جديد" },
      { slug: "mine", en: "My Projects", ar: "مشاريعي" },
      { slug: "priority", en: "Priority Projects", ar: "المشاريع ذات الأولوية" },
      { slug: "active", en: "Active Tasks", ar: "المهام النشطة" },
      { slug: "pending", en: "Pending Tasks", ar: "المهام المعلقة" },
      { slug: "completed", en: "Completed Tasks", ar: "المهام المنجزة" },
      { slug: "calendar", en: "Calendar", ar: "التقويم" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "quality", en: "Quality & Training", ar: "الجودة والتدريب", icon: ShieldCheck,
    desc_en: "Documents, audits, training, follow-up",
    desc_ar: "الوثائق والتدقيق والتدريب والمتابعة",
    items: [
      { slug: "documents", en: "Documents", ar: "الوثائق" },
      { slug: "audits", en: "Audits", ar: "التدقيق" },
      { slug: "training", en: "Training", ar: "التدريب" },
      { slug: "follow-up", en: "Quality Follow-up", ar: "متابعة الجودة" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "sms", en: "SMS", ar: "الرسائل القصيرة", icon: MessageSquare,
    desc_en: "Send, schedule and review SMS",
    desc_ar: "إرسال وجدولة ومراجعة الرسائل",
    items: [
      { slug: "send", en: "Send SMS", ar: "إرسال رسالة" },
      { slug: "auto", en: "Auto-send", ar: "الإرسال التلقائي" },
      { slug: "reports", en: "Reports", ar: "التقارير" },
    ],
  },
  {
    slug: "archive", en: "Documents & Archive", ar: "المستندات والأرشيف", icon: Archive,
    desc_en: "Archive, search, templates",
    desc_ar: "الأرشيف والبحث والقوالب",
    items: [
      { slug: "archive", en: "Archive", ar: "الأرشيف" },
      { slug: "search", en: "Search", ar: "البحث" },
      { slug: "templates", en: "Templates", ar: "القوالب" },
    ],
  },
  {
    slug: "admin", en: "Administration", ar: "البيانات الأساسية", icon: Settings,
    desc_en: "Settings, users, permissions, backups, designer",
    desc_ar: "الإعدادات والمستخدمون والصلاحيات والنسخ الاحتياطية والمصمم",
    items: [
      { slug: "settings", en: "System Settings", ar: "إعدادات النظام" },
      { slug: "basic-data", en: "Basic Data", ar: "البيانات الأساسية" },
      { slug: "banks", en: "Banks & Treasuries", ar: "البنوك والخزائن" },
      { slug: "news", en: "News", ar: "الأخبار" },
      { slug: "login-log", en: "Login Log", ar: "سجل الدخول" },
      { slug: "users", en: "Users", ar: "المستخدمون" },
      { slug: "groups", en: "User Groups", ar: "مجموعات المستخدمين" },
      { slug: "backup", en: "Database Backup", ar: "النسخ الاحتياطي" },
      { slug: "maintenance", en: "DB Maintenance", ar: "صيانة قاعدة البيانات" },
      { slug: "sql", en: "SQL Tool", ar: "أداة SQL" },
      { slug: "report-designer", en: "Report Designer", ar: "مصمم التقارير" },
      { slug: "apps", en: "App Management", ar: "إدارة التطبيقات" },
    ],
  },
];

export function findModule(slug: string) {
  return MODULES.find((m) => m.slug === slug);
}
