/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MModuleRouteImport } from './routes/m.$module'
import { Route as MModuleIndexRouteImport } from './routes/m.$module.index'
import { Route as MModuleSubRouteImport } from './routes/m.$module.$sub'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleRoute = MModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleIndexRoute = MModuleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MModuleRoute,
} as any)
const MModuleSubRoute = MModuleSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => MModuleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/m/$module/$sub': typeof MModuleSubRoute
  '/m/$module/': typeof MModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/m/$module/$sub': typeof MModuleSubRoute
  '/m/$module': typeof MModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/m/$module/$sub': typeof MModuleSubRoute
  '/m/$module/': typeof MModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/m/$module' | '/m/$module/$sub' | '/m/$module/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/m/$module/$sub' | '/m/$module'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/m/$module'
    | '/m/$module/$sub'
    | '/m/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MModuleRoute: typeof MModuleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module': {
      id: '/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof MModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module/': {
      id: '/m/$module/'
      path: '/'
      fullPath: '/m/$module/'
      preLoaderRoute: typeof MModuleIndexRouteImport
      parentRoute: typeof MModuleRoute
    }
    '/m/$module/$sub': {
      id: '/m/$module/$sub'
      path: '/$sub'
      fullPath: '/m/$module/$sub'
      preLoaderRoute: typeof MModuleSubRouteImport
      parentRoute: typeof MModuleRoute
    }
  }
}

interface MModuleRouteChildren {
  MModuleSubRoute: typeof MModuleSubRoute
  MModuleIndexRoute: typeof MModuleIndexRoute
}

const MModuleRouteChildren: MModuleRouteChildren = {
  MModuleSubRoute: MModuleSubRoute,
  MModuleIndexRoute: MModuleIndexRoute,
}

const MModuleRouteWithChildren =
  MModuleRoute._addFileChildren(MModuleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MModuleRoute: MModuleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
